### ISSUE TITLE
esphome-ensto not connecting to Ensto ELTE6-BT

### ISSUE THREAD

**Issue by ExMacro** [jumakki/esphome-ensto#9]
Hi!

I managed to install this very nice software to my ESP32 in the bathroom. The logs show that ESP32 sees the device and that it is in pairing mode. However, it gives an error -133 to the logs. Any idea on this? I tried to pair with the official Ensto app and it works flawlessly of course.

Thanks again for the very nice software!

```
[16:48:47][I][ensto.adv:052]: New BLE device
[16:48:47][I][ensto.adv:054]:   Advertised manufacturer data:
[16:48:47][I][ensto.adv:062]:     - ELTE6-BT;1;1;0;
[16:48:47][I][ensto.adv:072]:     - is pairing = true
[16:48:47][I][esp32_ble_client:067]: [0] [XX:XX:XX:XX:XX:XX] 0x00 Attempting BLE connection
[16:48:49][W][esp32_ble_client:143]: [0] [XX:XX:XX:XX:XX:XX] Connection failed, status=133

```

**Comment by ExMacro** [comment]
I'm using this ESP32 board. Might have something to do with its BLE capabilities. Any ideas are welcome!

https://piikauppa.fi/kauppa/mikrokontrollerit/esp32/esp32-ch340c-usb-c

**Comment by matkaan** [comment]
One tweak that you can also try: In last few days I have tested "power_save_mode: high" -wifi parameters on new boards that I got. It seems that this _might_ have helped on reliability on BLE-connection on some esp32 boards that I have had issues. Idea is that wifi would not create power peaks this might have affect esp32 reliability. And maybe safe some execution / radio time for bluetooth connection as they share same radio module on esp32. At least on good wifi connection, this setting seems not to cause any negative affect to esp32 wifi connection. So you could try this to see if it has any positive affect. Some of these cheap esp32 boards have really bad antennas, board with external antenna might also be an option (I have these also).

```
wifi:
 ssid: !secret wifi_ssid
 password: !secret wifi_password
 power_save_mode: high
```

**Comment by jumakki** [comment]
Factory reset step should not be needed but can of course be done. It would likely change the pairing key. I have never factory reset mine.

That error status code 133 (0x85 in hex) is just "Generic error" according to docs: https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/bluetooth/esp_gatt_defs.html
So that doesn't help.

You could try to change script from using "esp-idf" instead of default "arduino". It is claimed to be more stable and I'm planning to change script to use it by default. Unfortunately it is a breaking change and requires flashing with USB instead of using OTA.
It can be changed by changing beginning of script to contain:
```
esphome:
  name: esphome-ensto

esp32:
  #board: esp32dev
  board: esp32doit-devkit-v1
  #board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging. Note that too much logging will cause connections to break.
logger:
```
Rest of the script can be same.

If instructions from matkaan or changing to esp-idf doesn't help, you could try to increase logging levels.
For example
```
esp32_ble_client: DEBUG
```
instead of INFO could show more information instead of just error 133. But I don't have high hopes on that.
